language: node_js
node_js:
- lts/*
install:
- yarn install
script:
- yarn test
- yarn build
deploy:
  provider: pages
  local_dir: dist
  target_branch: master
  on:
    branch: develop
  token: "$GH_TOKEN"
  skip_cleanup: true
  keep_history: true
  committer_from_gh: true
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
