language: node_js
node_js:
- lts/*
branches:
  only:
  - main
cache:
  directories:
  - node_modules
install:
- npm install hexo-cli -g
- npm install
script:
- npm run deploy
deploy:
  provider: pages
  local_dir: dist
  target_branch: master
  on:
    branch: develop
  token: "$GH_TOKEN"
  skip_cleanup: true
  keep_history: true
  committer_from_gh: true
before_install:
- openssl aes-256-cbc -K $encrypted_e0d58fed9be7_key -iv $encrypted_e0d58fed9be7_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'BlackChen'
- git config --global user.email blackchen@best-developer.cn
